apiVersion: v1
kind: Service
metadata:
  name: hello-world-ops-service
  labels:
    app: hello-world-ops
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8090
    protocol: TCP
  selector:
    app: hello-world-ops 